// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: constraints.proto

package com.amazonaws.athena.lambda.connector.predicate;

/**
 * Protobuf type {@code com.amazonaws.athena.lambda.connector.predicate.Constraints}
 */
public  final class Constraints extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.amazonaws.athena.lambda.connector.predicate.Constraints)
    ConstraintsOrBuilder {
  // Use Constraints.newBuilder() to construct.
  private Constraints(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Constraints() {
    orderByList_ = java.util.Collections.emptyList();
    limit_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Constraints(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              orderByList_ = new java.util.ArrayList<com.amazonaws.athena.lambda.connector.predicate.OrderByField>();
              mutable_bitField0_ |= 0x00000001;
            }
            orderByList_.add(
                input.readMessage(com.amazonaws.athena.lambda.connector.predicate.OrderByField.parser(), extensionRegistry));
            break;
          }
          case 16: {

            limit_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        orderByList_ = java.util.Collections.unmodifiableList(orderByList_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.amazonaws.athena.lambda.connector.predicate.ConstraintsOuterClass.internal_static_com_amazonaws_athena_lambda_connector_predicate_Constraints_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.amazonaws.athena.lambda.connector.predicate.ConstraintsOuterClass.internal_static_com_amazonaws_athena_lambda_connector_predicate_Constraints_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.amazonaws.athena.lambda.connector.predicate.Constraints.class, com.amazonaws.athena.lambda.connector.predicate.Constraints.Builder.class);
  }

  private int bitField0_;
  public static final int ORDERBYLIST_FIELD_NUMBER = 1;
  private java.util.List<com.amazonaws.athena.lambda.connector.predicate.OrderByField> orderByList_;
  /**
   * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
   */
  public java.util.List<com.amazonaws.athena.lambda.connector.predicate.OrderByField> getOrderByListList() {
    return orderByList_;
  }
  /**
   * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
   */
  public java.util.List<? extends com.amazonaws.athena.lambda.connector.predicate.OrderByFieldOrBuilder> 
      getOrderByListOrBuilderList() {
    return orderByList_;
  }
  /**
   * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
   */
  public int getOrderByListCount() {
    return orderByList_.size();
  }
  /**
   * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
   */
  public com.amazonaws.athena.lambda.connector.predicate.OrderByField getOrderByList(int index) {
    return orderByList_.get(index);
  }
  /**
   * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
   */
  public com.amazonaws.athena.lambda.connector.predicate.OrderByFieldOrBuilder getOrderByListOrBuilder(
      int index) {
    return orderByList_.get(index);
  }

  public static final int LIMIT_FIELD_NUMBER = 2;
  private long limit_;
  /**
   * <code>optional int64 limit = 2;</code>
   */
  public long getLimit() {
    return limit_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < orderByList_.size(); i++) {
      output.writeMessage(1, orderByList_.get(i));
    }
    if (limit_ != 0L) {
      output.writeInt64(2, limit_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < orderByList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, orderByList_.get(i));
    }
    if (limit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, limit_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.amazonaws.athena.lambda.connector.predicate.Constraints)) {
      return super.equals(obj);
    }
    com.amazonaws.athena.lambda.connector.predicate.Constraints other = (com.amazonaws.athena.lambda.connector.predicate.Constraints) obj;

    boolean result = true;
    result = result && getOrderByListList()
        .equals(other.getOrderByListList());
    result = result && (getLimit()
        == other.getLimit());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getOrderByListCount() > 0) {
      hash = (37 * hash) + ORDERBYLIST_FIELD_NUMBER;
      hash = (53 * hash) + getOrderByListList().hashCode();
    }
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLimit());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.amazonaws.athena.lambda.connector.predicate.Constraints parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.Constraints parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.Constraints parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.Constraints parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.Constraints parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.Constraints parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.Constraints parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.Constraints parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.Constraints parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.Constraints parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.amazonaws.athena.lambda.connector.predicate.Constraints prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.amazonaws.athena.lambda.connector.predicate.Constraints}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.amazonaws.athena.lambda.connector.predicate.Constraints)
      com.amazonaws.athena.lambda.connector.predicate.ConstraintsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amazonaws.athena.lambda.connector.predicate.ConstraintsOuterClass.internal_static_com_amazonaws_athena_lambda_connector_predicate_Constraints_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amazonaws.athena.lambda.connector.predicate.ConstraintsOuterClass.internal_static_com_amazonaws_athena_lambda_connector_predicate_Constraints_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amazonaws.athena.lambda.connector.predicate.Constraints.class, com.amazonaws.athena.lambda.connector.predicate.Constraints.Builder.class);
    }

    // Construct using com.amazonaws.athena.lambda.connector.predicate.Constraints.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOrderByListFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (orderByListBuilder_ == null) {
        orderByList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        orderByListBuilder_.clear();
      }
      limit_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.amazonaws.athena.lambda.connector.predicate.ConstraintsOuterClass.internal_static_com_amazonaws_athena_lambda_connector_predicate_Constraints_descriptor;
    }

    public com.amazonaws.athena.lambda.connector.predicate.Constraints getDefaultInstanceForType() {
      return com.amazonaws.athena.lambda.connector.predicate.Constraints.getDefaultInstance();
    }

    public com.amazonaws.athena.lambda.connector.predicate.Constraints build() {
      com.amazonaws.athena.lambda.connector.predicate.Constraints result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.amazonaws.athena.lambda.connector.predicate.Constraints buildPartial() {
      com.amazonaws.athena.lambda.connector.predicate.Constraints result = new com.amazonaws.athena.lambda.connector.predicate.Constraints(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (orderByListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          orderByList_ = java.util.Collections.unmodifiableList(orderByList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.orderByList_ = orderByList_;
      } else {
        result.orderByList_ = orderByListBuilder_.build();
      }
      result.limit_ = limit_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.amazonaws.athena.lambda.connector.predicate.Constraints) {
        return mergeFrom((com.amazonaws.athena.lambda.connector.predicate.Constraints)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.amazonaws.athena.lambda.connector.predicate.Constraints other) {
      if (other == com.amazonaws.athena.lambda.connector.predicate.Constraints.getDefaultInstance()) return this;
      if (orderByListBuilder_ == null) {
        if (!other.orderByList_.isEmpty()) {
          if (orderByList_.isEmpty()) {
            orderByList_ = other.orderByList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOrderByListIsMutable();
            orderByList_.addAll(other.orderByList_);
          }
          onChanged();
        }
      } else {
        if (!other.orderByList_.isEmpty()) {
          if (orderByListBuilder_.isEmpty()) {
            orderByListBuilder_.dispose();
            orderByListBuilder_ = null;
            orderByList_ = other.orderByList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            orderByListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrderByListFieldBuilder() : null;
          } else {
            orderByListBuilder_.addAllMessages(other.orderByList_);
          }
        }
      }
      if (other.getLimit() != 0L) {
        setLimit(other.getLimit());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.amazonaws.athena.lambda.connector.predicate.Constraints parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.amazonaws.athena.lambda.connector.predicate.Constraints) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.amazonaws.athena.lambda.connector.predicate.OrderByField> orderByList_ =
      java.util.Collections.emptyList();
    private void ensureOrderByListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        orderByList_ = new java.util.ArrayList<com.amazonaws.athena.lambda.connector.predicate.OrderByField>(orderByList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.amazonaws.athena.lambda.connector.predicate.OrderByField, com.amazonaws.athena.lambda.connector.predicate.OrderByField.Builder, com.amazonaws.athena.lambda.connector.predicate.OrderByFieldOrBuilder> orderByListBuilder_;

    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public java.util.List<com.amazonaws.athena.lambda.connector.predicate.OrderByField> getOrderByListList() {
      if (orderByListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orderByList_);
      } else {
        return orderByListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public int getOrderByListCount() {
      if (orderByListBuilder_ == null) {
        return orderByList_.size();
      } else {
        return orderByListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public com.amazonaws.athena.lambda.connector.predicate.OrderByField getOrderByList(int index) {
      if (orderByListBuilder_ == null) {
        return orderByList_.get(index);
      } else {
        return orderByListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public Builder setOrderByList(
        int index, com.amazonaws.athena.lambda.connector.predicate.OrderByField value) {
      if (orderByListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderByListIsMutable();
        orderByList_.set(index, value);
        onChanged();
      } else {
        orderByListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public Builder setOrderByList(
        int index, com.amazonaws.athena.lambda.connector.predicate.OrderByField.Builder builderForValue) {
      if (orderByListBuilder_ == null) {
        ensureOrderByListIsMutable();
        orderByList_.set(index, builderForValue.build());
        onChanged();
      } else {
        orderByListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public Builder addOrderByList(com.amazonaws.athena.lambda.connector.predicate.OrderByField value) {
      if (orderByListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderByListIsMutable();
        orderByList_.add(value);
        onChanged();
      } else {
        orderByListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public Builder addOrderByList(
        int index, com.amazonaws.athena.lambda.connector.predicate.OrderByField value) {
      if (orderByListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderByListIsMutable();
        orderByList_.add(index, value);
        onChanged();
      } else {
        orderByListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public Builder addOrderByList(
        com.amazonaws.athena.lambda.connector.predicate.OrderByField.Builder builderForValue) {
      if (orderByListBuilder_ == null) {
        ensureOrderByListIsMutable();
        orderByList_.add(builderForValue.build());
        onChanged();
      } else {
        orderByListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public Builder addOrderByList(
        int index, com.amazonaws.athena.lambda.connector.predicate.OrderByField.Builder builderForValue) {
      if (orderByListBuilder_ == null) {
        ensureOrderByListIsMutable();
        orderByList_.add(index, builderForValue.build());
        onChanged();
      } else {
        orderByListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public Builder addAllOrderByList(
        java.lang.Iterable<? extends com.amazonaws.athena.lambda.connector.predicate.OrderByField> values) {
      if (orderByListBuilder_ == null) {
        ensureOrderByListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orderByList_);
        onChanged();
      } else {
        orderByListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public Builder clearOrderByList() {
      if (orderByListBuilder_ == null) {
        orderByList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        orderByListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public Builder removeOrderByList(int index) {
      if (orderByListBuilder_ == null) {
        ensureOrderByListIsMutable();
        orderByList_.remove(index);
        onChanged();
      } else {
        orderByListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public com.amazonaws.athena.lambda.connector.predicate.OrderByField.Builder getOrderByListBuilder(
        int index) {
      return getOrderByListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public com.amazonaws.athena.lambda.connector.predicate.OrderByFieldOrBuilder getOrderByListOrBuilder(
        int index) {
      if (orderByListBuilder_ == null) {
        return orderByList_.get(index);  } else {
        return orderByListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public java.util.List<? extends com.amazonaws.athena.lambda.connector.predicate.OrderByFieldOrBuilder> 
         getOrderByListOrBuilderList() {
      if (orderByListBuilder_ != null) {
        return orderByListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orderByList_);
      }
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public com.amazonaws.athena.lambda.connector.predicate.OrderByField.Builder addOrderByListBuilder() {
      return getOrderByListFieldBuilder().addBuilder(
          com.amazonaws.athena.lambda.connector.predicate.OrderByField.getDefaultInstance());
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public com.amazonaws.athena.lambda.connector.predicate.OrderByField.Builder addOrderByListBuilder(
        int index) {
      return getOrderByListFieldBuilder().addBuilder(
          index, com.amazonaws.athena.lambda.connector.predicate.OrderByField.getDefaultInstance());
    }
    /**
     * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
     */
    public java.util.List<com.amazonaws.athena.lambda.connector.predicate.OrderByField.Builder> 
         getOrderByListBuilderList() {
      return getOrderByListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.amazonaws.athena.lambda.connector.predicate.OrderByField, com.amazonaws.athena.lambda.connector.predicate.OrderByField.Builder, com.amazonaws.athena.lambda.connector.predicate.OrderByFieldOrBuilder> 
        getOrderByListFieldBuilder() {
      if (orderByListBuilder_ == null) {
        orderByListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.amazonaws.athena.lambda.connector.predicate.OrderByField, com.amazonaws.athena.lambda.connector.predicate.OrderByField.Builder, com.amazonaws.athena.lambda.connector.predicate.OrderByFieldOrBuilder>(
                orderByList_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        orderByList_ = null;
      }
      return orderByListBuilder_;
    }

    private long limit_ ;
    /**
     * <code>optional int64 limit = 2;</code>
     */
    public long getLimit() {
      return limit_;
    }
    /**
     * <code>optional int64 limit = 2;</code>
     */
    public Builder setLimit(long value) {
      
      limit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 limit = 2;</code>
     */
    public Builder clearLimit() {
      
      limit_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.amazonaws.athena.lambda.connector.predicate.Constraints)
  }

  // @@protoc_insertion_point(class_scope:com.amazonaws.athena.lambda.connector.predicate.Constraints)
  private static final com.amazonaws.athena.lambda.connector.predicate.Constraints DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.amazonaws.athena.lambda.connector.predicate.Constraints();
  }

  public static com.amazonaws.athena.lambda.connector.predicate.Constraints getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Constraints>
      PARSER = new com.google.protobuf.AbstractParser<Constraints>() {
    public Constraints parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Constraints(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Constraints> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Constraints> getParserForType() {
    return PARSER;
  }

  public com.amazonaws.athena.lambda.connector.predicate.Constraints getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

