// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: constraints.proto

package com.amazonaws.athena.lambda.connector.predicate;

public interface ConstraintsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.amazonaws.athena.lambda.connector.predicate.Constraints)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
   */
  java.util.List<com.amazonaws.athena.lambda.connector.predicate.OrderByField> 
      getOrderByListList();
  /**
   * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
   */
  com.amazonaws.athena.lambda.connector.predicate.OrderByField getOrderByList(int index);
  /**
   * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
   */
  int getOrderByListCount();
  /**
   * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
   */
  java.util.List<? extends com.amazonaws.athena.lambda.connector.predicate.OrderByFieldOrBuilder> 
      getOrderByListOrBuilderList();
  /**
   * <code>repeated .com.amazonaws.athena.lambda.connector.predicate.OrderByField orderByList = 1;</code>
   */
  com.amazonaws.athena.lambda.connector.predicate.OrderByFieldOrBuilder getOrderByListOrBuilder(
      int index);

  /**
   * <code>optional int64 limit = 2;</code>
   */
  long getLimit();
}
