// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: constraints.proto

package com.amazonaws.athena.lambda.connector.predicate;

public final class ConstraintsOuterClass {
  private ConstraintsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amazonaws_athena_lambda_connector_predicate_Constraints_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amazonaws_athena_lambda_connector_predicate_Constraints_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amazonaws_athena_lambda_connector_predicate_OrderByField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amazonaws_athena_lambda_connector_predicate_OrderByField_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021constraints.proto\022/com.amazonaws.athen" +
      "a.lambda.connector.predicate\"p\n\013Constrai" +
      "nts\022R\n\013orderByList\030\001 \003(\0132=.com.amazonaws" +
      ".athena.lambda.connector.predicate.Order" +
      "ByField\022\r\n\005limit\030\002 \001(\003\"8\n\014OrderByField\022\022" +
      "\n\ncolumnName\030\001 \001(\t\022\024\n\014isDescending\030\002 \001(\010" +
      "B3\n/com.amazonaws.athena.lambda.connecto" +
      "r.predicateP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_amazonaws_athena_lambda_connector_predicate_Constraints_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_amazonaws_athena_lambda_connector_predicate_Constraints_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amazonaws_athena_lambda_connector_predicate_Constraints_descriptor,
        new java.lang.String[] { "OrderByList", "Limit", });
    internal_static_com_amazonaws_athena_lambda_connector_predicate_OrderByField_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_amazonaws_athena_lambda_connector_predicate_OrderByField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amazonaws_athena_lambda_connector_predicate_OrderByField_descriptor,
        new java.lang.String[] { "ColumnName", "IsDescending", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
