// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: constraints.proto

package com.amazonaws.athena.lambda.connector.predicate;

/**
 * Protobuf type {@code com.amazonaws.athena.lambda.connector.predicate.OrderByField}
 */
public  final class OrderByField extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.amazonaws.athena.lambda.connector.predicate.OrderByField)
    OrderByFieldOrBuilder {
  // Use OrderByField.newBuilder() to construct.
  private OrderByField(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderByField() {
    columnName_ = "";
    isDescending_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private OrderByField(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            columnName_ = s;
            break;
          }
          case 16: {

            isDescending_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.amazonaws.athena.lambda.connector.predicate.ConstraintsOuterClass.internal_static_com_amazonaws_athena_lambda_connector_predicate_OrderByField_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.amazonaws.athena.lambda.connector.predicate.ConstraintsOuterClass.internal_static_com_amazonaws_athena_lambda_connector_predicate_OrderByField_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.amazonaws.athena.lambda.connector.predicate.OrderByField.class, com.amazonaws.athena.lambda.connector.predicate.OrderByField.Builder.class);
  }

  public static final int COLUMNNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object columnName_;
  /**
   * <code>optional string columnName = 1;</code>
   */
  public java.lang.String getColumnName() {
    java.lang.Object ref = columnName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      columnName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string columnName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getColumnNameBytes() {
    java.lang.Object ref = columnName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      columnName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISDESCENDING_FIELD_NUMBER = 2;
  private boolean isDescending_;
  /**
   * <code>optional bool isDescending = 2;</code>
   */
  public boolean getIsDescending() {
    return isDescending_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getColumnNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, columnName_);
    }
    if (isDescending_ != false) {
      output.writeBool(2, isDescending_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getColumnNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, columnName_);
    }
    if (isDescending_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isDescending_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.amazonaws.athena.lambda.connector.predicate.OrderByField)) {
      return super.equals(obj);
    }
    com.amazonaws.athena.lambda.connector.predicate.OrderByField other = (com.amazonaws.athena.lambda.connector.predicate.OrderByField) obj;

    boolean result = true;
    result = result && getColumnName()
        .equals(other.getColumnName());
    result = result && (getIsDescending()
        == other.getIsDescending());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + COLUMNNAME_FIELD_NUMBER;
    hash = (53 * hash) + getColumnName().hashCode();
    hash = (37 * hash) + ISDESCENDING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDescending());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.amazonaws.athena.lambda.connector.predicate.OrderByField parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.OrderByField parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.OrderByField parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.OrderByField parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.OrderByField parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.OrderByField parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.OrderByField parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.OrderByField parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.OrderByField parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amazonaws.athena.lambda.connector.predicate.OrderByField parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.amazonaws.athena.lambda.connector.predicate.OrderByField prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.amazonaws.athena.lambda.connector.predicate.OrderByField}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.amazonaws.athena.lambda.connector.predicate.OrderByField)
      com.amazonaws.athena.lambda.connector.predicate.OrderByFieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amazonaws.athena.lambda.connector.predicate.ConstraintsOuterClass.internal_static_com_amazonaws_athena_lambda_connector_predicate_OrderByField_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amazonaws.athena.lambda.connector.predicate.ConstraintsOuterClass.internal_static_com_amazonaws_athena_lambda_connector_predicate_OrderByField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amazonaws.athena.lambda.connector.predicate.OrderByField.class, com.amazonaws.athena.lambda.connector.predicate.OrderByField.Builder.class);
    }

    // Construct using com.amazonaws.athena.lambda.connector.predicate.OrderByField.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      columnName_ = "";

      isDescending_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.amazonaws.athena.lambda.connector.predicate.ConstraintsOuterClass.internal_static_com_amazonaws_athena_lambda_connector_predicate_OrderByField_descriptor;
    }

    public com.amazonaws.athena.lambda.connector.predicate.OrderByField getDefaultInstanceForType() {
      return com.amazonaws.athena.lambda.connector.predicate.OrderByField.getDefaultInstance();
    }

    public com.amazonaws.athena.lambda.connector.predicate.OrderByField build() {
      com.amazonaws.athena.lambda.connector.predicate.OrderByField result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.amazonaws.athena.lambda.connector.predicate.OrderByField buildPartial() {
      com.amazonaws.athena.lambda.connector.predicate.OrderByField result = new com.amazonaws.athena.lambda.connector.predicate.OrderByField(this);
      result.columnName_ = columnName_;
      result.isDescending_ = isDescending_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.amazonaws.athena.lambda.connector.predicate.OrderByField) {
        return mergeFrom((com.amazonaws.athena.lambda.connector.predicate.OrderByField)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.amazonaws.athena.lambda.connector.predicate.OrderByField other) {
      if (other == com.amazonaws.athena.lambda.connector.predicate.OrderByField.getDefaultInstance()) return this;
      if (!other.getColumnName().isEmpty()) {
        columnName_ = other.columnName_;
        onChanged();
      }
      if (other.getIsDescending() != false) {
        setIsDescending(other.getIsDescending());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.amazonaws.athena.lambda.connector.predicate.OrderByField parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.amazonaws.athena.lambda.connector.predicate.OrderByField) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object columnName_ = "";
    /**
     * <code>optional string columnName = 1;</code>
     */
    public java.lang.String getColumnName() {
      java.lang.Object ref = columnName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        columnName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string columnName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getColumnNameBytes() {
      java.lang.Object ref = columnName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        columnName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string columnName = 1;</code>
     */
    public Builder setColumnName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      columnName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string columnName = 1;</code>
     */
    public Builder clearColumnName() {
      
      columnName_ = getDefaultInstance().getColumnName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string columnName = 1;</code>
     */
    public Builder setColumnNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      columnName_ = value;
      onChanged();
      return this;
    }

    private boolean isDescending_ ;
    /**
     * <code>optional bool isDescending = 2;</code>
     */
    public boolean getIsDescending() {
      return isDescending_;
    }
    /**
     * <code>optional bool isDescending = 2;</code>
     */
    public Builder setIsDescending(boolean value) {
      
      isDescending_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isDescending = 2;</code>
     */
    public Builder clearIsDescending() {
      
      isDescending_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.amazonaws.athena.lambda.connector.predicate.OrderByField)
  }

  // @@protoc_insertion_point(class_scope:com.amazonaws.athena.lambda.connector.predicate.OrderByField)
  private static final com.amazonaws.athena.lambda.connector.predicate.OrderByField DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.amazonaws.athena.lambda.connector.predicate.OrderByField();
  }

  public static com.amazonaws.athena.lambda.connector.predicate.OrderByField getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderByField>
      PARSER = new com.google.protobuf.AbstractParser<OrderByField>() {
    public OrderByField parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderByField(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderByField> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderByField> getParserForType() {
    return PARSER;
  }

  public com.amazonaws.athena.lambda.connector.predicate.OrderByField getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

