// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: constraints.proto

package com.amazonaws.athena.lambda.connector.predicate;

public interface OrderByFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.amazonaws.athena.lambda.connector.predicate.OrderByField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string columnName = 1;</code>
   */
  java.lang.String getColumnName();
  /**
   * <code>optional string columnName = 1;</code>
   */
  com.google.protobuf.ByteString
      getColumnNameBytes();

  /**
   * <code>optional bool isDescending = 2;</code>
   */
  boolean getIsDescending();
}
